# Generated by Django 2.0.3 on 2018-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_html', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
