# Generated by Django 2.0.3 on 2018-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_html', '0003_readed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readed',
            old_name='readedbook',
            new_name='reader',
        ),
        migrations.RemoveField(
            model_name='readed',
            name='readed_url',
        ),
        migrations.AlterField(
            model_name='readed',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
