# Generated by Django 2.0.3 on 2018-04-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_html', '0004_auto_20180427_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readed',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
